//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceSICOP
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cata.co.cr", ConfigurationName="ServiceReferenceSICOP.CataWebService")]
    public interface CataWebService
    {
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceSICOP.DetailCodigoClasificacionResponse> DetailCodigoClasificacionAsync(ServiceReferenceSICOP.DetailCodigoClasificacionRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceSICOP.ListadoCodigoClasificacionResponse> ListadoCodigoClasificacionAsync(ServiceReferenceSICOP.ListadoCodigoClasificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceSICOP.getItemInfoResponse> getItemInfoAsync(ServiceReferenceSICOP.getItemInfoRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceSICOP.ListadoSegmentosResponse> ListadoSegmentosAsync(ServiceReferenceSICOP.ListadoSegmentosRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceSICOP.ListadoProductosResponse> ListadoProductosAsync(ServiceReferenceSICOP.ListadoProductosRequest request);
        
        // CODEGEN: Generando contrato de mensaje, ya que la operación tiene múltiples valores devueltos.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceSICOP.ListadoAtributosResponse> ListadoAtributosAsync(ServiceReferenceSICOP.ListadoAtributosRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:webservice.vo")]
    public partial class AuthHeader
    {
        
        private string passwordField;
        
        private string userNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataAttributeListBean
    {
        
        private string attr_clField;
        
        private string attr_descField;
        
        private string attr_idField;
        
        private string attr_lenField;
        
        private string attr_nmField;
        
        private string attr_nm_enField;
        
        private string data_typeField;
        
        private string input_typeField;
        
        private System.Nullable<System.DateTime> mod_dtField;
        
        private System.Nullable<System.DateTime> reg_dtField;
        
        private string use_ynField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Attr_cl
        {
            get
            {
                return this.attr_clField;
            }
            set
            {
                this.attr_clField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Attr_desc
        {
            get
            {
                return this.attr_descField;
            }
            set
            {
                this.attr_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Attr_id
        {
            get
            {
                return this.attr_idField;
            }
            set
            {
                this.attr_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Attr_len
        {
            get
            {
                return this.attr_lenField;
            }
            set
            {
                this.attr_lenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Attr_nm
        {
            get
            {
                return this.attr_nmField;
            }
            set
            {
                this.attr_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Attr_nm_en
        {
            get
            {
                return this.attr_nm_enField;
            }
            set
            {
                this.attr_nm_enField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Data_type
        {
            get
            {
                return this.data_typeField;
            }
            set
            {
                this.data_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Input_type
        {
            get
            {
                return this.input_typeField;
            }
            set
            {
                this.input_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public System.Nullable<System.DateTime> Mod_dt
        {
            get
            {
                return this.mod_dtField;
            }
            set
            {
                this.mod_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> Reg_dt
        {
            get
            {
                return this.reg_dtField;
            }
            set
            {
                this.reg_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string Use_yn
        {
            get
            {
                return this.use_ynField;
            }
            set
            {
                this.use_ynField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataListadoAtributosResponseBean
    {
        
        private CataAttributeListBean[] attr_listField;
        
        private string errordescriptionField;
        
        private string resultadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attr_list", IsNullable=true, Order=0)]
        public CataAttributeListBean[] Attr_list
        {
            get
            {
                return this.attr_listField;
            }
            set
            {
                this.attr_listField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Errordescription
        {
            get
            {
                return this.errordescriptionField;
            }
            set
            {
                this.errordescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataListadoAtributosRequestBean
    {
        
        private System.Nullable<System.DateTime> from_DateField;
        
        private System.Nullable<System.DateTime> to_DateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> From_Date
        {
            get
            {
                return this.from_DateField;
            }
            set
            {
                this.from_DateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> To_Date
        {
            get
            {
                return this.to_DateField;
            }
            set
            {
                this.to_DateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataProductBean
    {
        
        private System.Nullable<System.DateTime> mod_dtField;
        
        private string prod_idField;
        
        private string prod_nmField;
        
        private System.Nullable<System.DateTime> reg_dtField;
        
        private string use_ynField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public System.Nullable<System.DateTime> Mod_dt
        {
            get
            {
                return this.mod_dtField;
            }
            set
            {
                this.mod_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Prod_id
        {
            get
            {
                return this.prod_idField;
            }
            set
            {
                this.prod_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Prod_nm
        {
            get
            {
                return this.prod_nmField;
            }
            set
            {
                this.prod_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> Reg_dt
        {
            get
            {
                return this.reg_dtField;
            }
            set
            {
                this.reg_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Use_yn
        {
            get
            {
                return this.use_ynField;
            }
            set
            {
                this.use_ynField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataProductResponse
    {
        
        private string errorDescriptionField;
        
        private CataProductBean[] prod_listField;
        
        private string resultadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Prod_list", IsNullable=true, Order=1)]
        public CataProductBean[] Prod_list
        {
            get
            {
                return this.prod_listField;
            }
            set
            {
                this.prod_listField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataProductRequest
    {
        
        private string code_idField;
        
        private string code_typeField;
        
        private System.Nullable<System.DateTime> from_dateField;
        
        private System.Nullable<System.DateTime> to_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Code_id
        {
            get
            {
                return this.code_idField;
            }
            set
            {
                this.code_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Code_type
        {
            get
            {
                return this.code_typeField;
            }
            set
            {
                this.code_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> From_date
        {
            get
            {
                return this.from_dateField;
            }
            set
            {
                this.from_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> To_date
        {
            get
            {
                return this.to_dateField;
            }
            set
            {
                this.to_dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataCateSegmentBean
    {
        
        private string cate_idField;
        
        private string cate_nmField;
        
        private System.Nullable<System.DateTime> mod_dtField;
        
        private System.Nullable<System.DateTime> reg_dtField;
        
        private string use_ynField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Cate_id
        {
            get
            {
                return this.cate_idField;
            }
            set
            {
                this.cate_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Cate_nm
        {
            get
            {
                return this.cate_nmField;
            }
            set
            {
                this.cate_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> Mod_dt
        {
            get
            {
                return this.mod_dtField;
            }
            set
            {
                this.mod_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> Reg_dt
        {
            get
            {
                return this.reg_dtField;
            }
            set
            {
                this.reg_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Use_yn
        {
            get
            {
                return this.use_ynField;
            }
            set
            {
                this.use_ynField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataSegmentResponse
    {
        
        private CataCateSegmentBean[] cate_listField;
        
        private string errorDescriptionField;
        
        private string resultadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cate_list", IsNullable=true, Order=0)]
        public CataCateSegmentBean[] Cate_list
        {
            get
            {
                return this.cate_listField;
            }
            set
            {
                this.cate_listField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataSegmentRequest
    {
        
        private string cate_reqField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Cate_req
        {
            get
            {
                return this.cate_reqField;
            }
            set
            {
                this.cate_reqField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataItemAttrListBean
    {
        
        private string attr_idField;
        
        private string attr_nmField;
        
        private string attr_valueField;
        
        private string attr_value_unidadField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Attr_id
        {
            get
            {
                return this.attr_idField;
            }
            set
            {
                this.attr_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Attr_nm
        {
            get
            {
                return this.attr_nmField;
            }
            set
            {
                this.attr_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Attr_value
        {
            get
            {
                return this.attr_valueField;
            }
            set
            {
                this.attr_valueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Attr_value_unidad
        {
            get
            {
                return this.attr_value_unidadField;
            }
            set
            {
                this.attr_value_unidadField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataItemAttachment
    {
        
        private string file_nmField;
        
        private string file_sizeField;
        
        private string file_typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string File_nm
        {
            get
            {
                return this.file_nmField;
            }
            set
            {
                this.file_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string File_size
        {
            get
            {
                return this.file_sizeField;
            }
            set
            {
                this.file_sizeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string File_type
        {
            get
            {
                return this.file_typeField;
            }
            set
            {
                this.file_typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataItemResponse
    {
        
        private CataItemAttachment[] attachListField;
        
        private int attachment_cntField;
        
        private CataItemAttrListBean[] attrListField;
        
        private string brand_nmField;
        
        private string cate_idField;
        
        private string cate_nmField;
        
        private string cate_nm_enField;
        
        private string comp_cdField;
        
        private string comp_nmField;
        
        private string env_labelField;
        
        private string errordescriptionField;
        
        private string expense_cdField;
        
        private string gtinField;
        
        private string handl_infoField;
        
        private string harz_cdField;
        
        private string hs_cdField;
        
        private string info_glnField;
        
        private string ingr_markField;
        
        private string inst_prod_nmField;
        
        private System.Nullable<System.DateTime> mod_dtField;
        
        private string model_nmField;
        
        private string pac_recyField;
        
        private string pac_typeField;
        
        private string pac_unitField;
        
        private string prod_descField;
        
        private string prod_idField;
        
        private int prod_lifeField;
        
        private string prod_nmField;
        
        private string prod_oriField;
        
        private string prod_recyField;
        
        private string prod_unitField;
        
        private System.Nullable<System.DateTime> reg_dtField;
        
        private string resultadoField;
        
        private string rpgtinField;
        
        private string three_authenticationField;
        
        private string use_ynField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttachList", IsNullable=true, Order=0)]
        public CataItemAttachment[] AttachList
        {
            get
            {
                return this.attachListField;
            }
            set
            {
                this.attachListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Attachment_cnt
        {
            get
            {
                return this.attachment_cntField;
            }
            set
            {
                this.attachment_cntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AttrList", IsNullable=true, Order=2)]
        public CataItemAttrListBean[] AttrList
        {
            get
            {
                return this.attrListField;
            }
            set
            {
                this.attrListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Brand_nm
        {
            get
            {
                return this.brand_nmField;
            }
            set
            {
                this.brand_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Cate_id
        {
            get
            {
                return this.cate_idField;
            }
            set
            {
                this.cate_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Cate_nm
        {
            get
            {
                return this.cate_nmField;
            }
            set
            {
                this.cate_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Cate_nm_en
        {
            get
            {
                return this.cate_nm_enField;
            }
            set
            {
                this.cate_nm_enField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Comp_cd
        {
            get
            {
                return this.comp_cdField;
            }
            set
            {
                this.comp_cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Comp_nm
        {
            get
            {
                return this.comp_nmField;
            }
            set
            {
                this.comp_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public string Env_label
        {
            get
            {
                return this.env_labelField;
            }
            set
            {
                this.env_labelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public string Errordescription
        {
            get
            {
                return this.errordescriptionField;
            }
            set
            {
                this.errordescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string Expense_cd
        {
            get
            {
                return this.expense_cdField;
            }
            set
            {
                this.expense_cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string Gtin
        {
            get
            {
                return this.gtinField;
            }
            set
            {
                this.gtinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string Handl_info
        {
            get
            {
                return this.handl_infoField;
            }
            set
            {
                this.handl_infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=14)]
        public string Harz_cd
        {
            get
            {
                return this.harz_cdField;
            }
            set
            {
                this.harz_cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=15)]
        public string Hs_cd
        {
            get
            {
                return this.hs_cdField;
            }
            set
            {
                this.hs_cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=16)]
        public string Info_gln
        {
            get
            {
                return this.info_glnField;
            }
            set
            {
                this.info_glnField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=17)]
        public string Ingr_mark
        {
            get
            {
                return this.ingr_markField;
            }
            set
            {
                this.ingr_markField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public string Inst_prod_nm
        {
            get
            {
                return this.inst_prod_nmField;
            }
            set
            {
                this.inst_prod_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<System.DateTime> Mod_dt
        {
            get
            {
                return this.mod_dtField;
            }
            set
            {
                this.mod_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public string Model_nm
        {
            get
            {
                return this.model_nmField;
            }
            set
            {
                this.model_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=21)]
        public string Pac_recy
        {
            get
            {
                return this.pac_recyField;
            }
            set
            {
                this.pac_recyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=22)]
        public string Pac_type
        {
            get
            {
                return this.pac_typeField;
            }
            set
            {
                this.pac_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=23)]
        public string Pac_unit
        {
            get
            {
                return this.pac_unitField;
            }
            set
            {
                this.pac_unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=24)]
        public string Prod_desc
        {
            get
            {
                return this.prod_descField;
            }
            set
            {
                this.prod_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=25)]
        public string Prod_id
        {
            get
            {
                return this.prod_idField;
            }
            set
            {
                this.prod_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public int Prod_life
        {
            get
            {
                return this.prod_lifeField;
            }
            set
            {
                this.prod_lifeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=27)]
        public string Prod_nm
        {
            get
            {
                return this.prod_nmField;
            }
            set
            {
                this.prod_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=28)]
        public string Prod_ori
        {
            get
            {
                return this.prod_oriField;
            }
            set
            {
                this.prod_oriField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=29)]
        public string Prod_recy
        {
            get
            {
                return this.prod_recyField;
            }
            set
            {
                this.prod_recyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=30)]
        public string Prod_unit
        {
            get
            {
                return this.prod_unitField;
            }
            set
            {
                this.prod_unitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=31)]
        public System.Nullable<System.DateTime> Reg_dt
        {
            get
            {
                return this.reg_dtField;
            }
            set
            {
                this.reg_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=32)]
        public string Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=33)]
        public string Rpgtin
        {
            get
            {
                return this.rpgtinField;
            }
            set
            {
                this.rpgtinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=34)]
        public string Three_authentication
        {
            get
            {
                return this.three_authenticationField;
            }
            set
            {
                this.three_authenticationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=35)]
        public string Use_yn
        {
            get
            {
                return this.use_ynField;
            }
            set
            {
                this.use_ynField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataItemRequest
    {
        
        private string cate_idField;
        
        private string prod_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Cate_id
        {
            get
            {
                return this.cate_idField;
            }
            set
            {
                this.cate_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Prod_id
        {
            get
            {
                return this.prod_idField;
            }
            set
            {
                this.prod_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataCateBean
    {
        
        private string cate_idField;
        
        private string cate_nmField;
        
        private string depthField;
        
        private System.Nullable<System.DateTime> mod_dtField;
        
        private System.Nullable<System.DateTime> reg_dtField;
        
        private string upper_idField;
        
        private string use_ynField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Cate_id
        {
            get
            {
                return this.cate_idField;
            }
            set
            {
                this.cate_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Cate_nm
        {
            get
            {
                return this.cate_nmField;
            }
            set
            {
                this.cate_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Depth
        {
            get
            {
                return this.depthField;
            }
            set
            {
                this.depthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public System.Nullable<System.DateTime> Mod_dt
        {
            get
            {
                return this.mod_dtField;
            }
            set
            {
                this.mod_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public System.Nullable<System.DateTime> Reg_dt
        {
            get
            {
                return this.reg_dtField;
            }
            set
            {
                this.reg_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Upper_id
        {
            get
            {
                return this.upper_idField;
            }
            set
            {
                this.upper_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string Use_yn
        {
            get
            {
                return this.use_ynField;
            }
            set
            {
                this.use_ynField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataCodeClassificationResponse
    {
        
        private CataCateBean[] cate_listField;
        
        private string errorDescriptionField;
        
        private string resultadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Cate_list", IsNullable=true, Order=0)]
        public CataCateBean[] Cate_list
        {
            get
            {
                return this.cate_listField;
            }
            set
            {
                this.cate_listField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataCodeClassificationRequest
    {
        
        private string cate_idField;
        
        private System.Nullable<System.DateTime> from_dateField;
        
        private System.Nullable<System.DateTime> to_dateField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Cate_id
        {
            get
            {
                return this.cate_idField;
            }
            set
            {
                this.cate_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<System.DateTime> From_date
        {
            get
            {
                return this.from_dateField;
            }
            set
            {
                this.from_dateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> To_date
        {
            get
            {
                return this.to_dateField;
            }
            set
            {
                this.to_dateField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataAttributeBean
    {
        
        private string attr_descField;
        
        private string attr_idField;
        
        private string attr_lenField;
        
        private string attr_nmField;
        
        private string data_typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Attr_desc
        {
            get
            {
                return this.attr_descField;
            }
            set
            {
                this.attr_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Attr_id
        {
            get
            {
                return this.attr_idField;
            }
            set
            {
                this.attr_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Attr_len
        {
            get
            {
                return this.attr_lenField;
            }
            set
            {
                this.attr_lenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Attr_nm
        {
            get
            {
                return this.attr_nmField;
            }
            set
            {
                this.attr_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Data_type
        {
            get
            {
                return this.data_typeField;
            }
            set
            {
                this.data_typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataDetailClassificationResponse
    {
        
        private CataAttributeBean[] attr_listField;
        
        private string cate_descField;
        
        private string cate_idField;
        
        private string cate_nmField;
        
        private string cate_nm_enField;
        
        private string depthField;
        
        private string errorDescriptionField;
        
        private string expense_cdField;
        
        private string hs_cdField;
        
        private System.Nullable<System.DateTime> mod_dtField;
        
        private System.Nullable<System.DateTime> reg_dtField;
        
        private string resultadoField;
        
        private string upper_idField;
        
        private string use_ynField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Attr_list", IsNullable=true, Order=0)]
        public CataAttributeBean[] Attr_list
        {
            get
            {
                return this.attr_listField;
            }
            set
            {
                this.attr_listField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Cate_desc
        {
            get
            {
                return this.cate_descField;
            }
            set
            {
                this.cate_descField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string Cate_id
        {
            get
            {
                return this.cate_idField;
            }
            set
            {
                this.cate_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Cate_nm
        {
            get
            {
                return this.cate_nmField;
            }
            set
            {
                this.cate_nmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Cate_nm_en
        {
            get
            {
                return this.cate_nm_enField;
            }
            set
            {
                this.cate_nm_enField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string Depth
        {
            get
            {
                return this.depthField;
            }
            set
            {
                this.depthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Expense_cd
        {
            get
            {
                return this.expense_cdField;
            }
            set
            {
                this.expense_cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string Hs_cd
        {
            get
            {
                return this.hs_cdField;
            }
            set
            {
                this.hs_cdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<System.DateTime> Mod_dt
        {
            get
            {
                return this.mod_dtField;
            }
            set
            {
                this.mod_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=10)]
        public System.Nullable<System.DateTime> Reg_dt
        {
            get
            {
                return this.reg_dtField;
            }
            set
            {
                this.reg_dtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
        public string Resultado
        {
            get
            {
                return this.resultadoField;
            }
            set
            {
                this.resultadoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=12)]
        public string Upper_id
        {
            get
            {
                return this.upper_idField;
            }
            set
            {
                this.upper_idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=13)]
        public string Use_yn
        {
            get
            {
                return this.use_ynField;
            }
            set
            {
                this.use_ynField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="java:ws.cata.bean")]
    public partial class CataDetailClassificationRequest
    {
        
        private string cate_idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Cate_id
        {
            get
            {
                return this.cate_idField;
            }
            set
            {
                this.cate_idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cata.co.cr")]
    public partial class DetailCodigoClasificacion
    {
        
        private CataDetailClassificationRequest cataInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CataDetailClassificationRequest cataInfo
        {
            get
            {
                return this.cataInfoField;
            }
            set
            {
                this.cataInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DetailCodigoClasificacionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cata.co.cr")]
        public ServiceReferenceSICOP.AuthHeader authHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.DetailCodigoClasificacion DetailCodigoClasificacion;
        
        public DetailCodigoClasificacionRequest()
        {
        }
        
        public DetailCodigoClasificacionRequest(ServiceReferenceSICOP.AuthHeader authHeader, ServiceReferenceSICOP.DetailCodigoClasificacion DetailCodigoClasificacion)
        {
            this.authHeader = authHeader;
            this.DetailCodigoClasificacion = DetailCodigoClasificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="DetailCodigoClasificacionResponse", WrapperNamespace="http://www.cata.co.cr", IsWrapped=true)]
    public partial class DetailCodigoClasificacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.CataDetailClassificationResponse DetailCodigoClasificacion;
        
        public DetailCodigoClasificacionResponse()
        {
        }
        
        public DetailCodigoClasificacionResponse(ServiceReferenceSICOP.CataDetailClassificationResponse DetailCodigoClasificacion)
        {
            this.DetailCodigoClasificacion = DetailCodigoClasificacion;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cata.co.cr")]
    public partial class ListadoCodigoClasificacion
    {
        
        private CataCodeClassificationRequest cataInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CataCodeClassificationRequest cataInfo
        {
            get
            {
                return this.cataInfoField;
            }
            set
            {
                this.cataInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListadoCodigoClasificacionRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cata.co.cr")]
        public ServiceReferenceSICOP.AuthHeader authHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.ListadoCodigoClasificacion ListadoCodigoClasificacion;
        
        public ListadoCodigoClasificacionRequest()
        {
        }
        
        public ListadoCodigoClasificacionRequest(ServiceReferenceSICOP.AuthHeader authHeader, ServiceReferenceSICOP.ListadoCodigoClasificacion ListadoCodigoClasificacion)
        {
            this.authHeader = authHeader;
            this.ListadoCodigoClasificacion = ListadoCodigoClasificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListadoCodigoClasificacionResponse", WrapperNamespace="http://www.cata.co.cr", IsWrapped=true)]
    public partial class ListadoCodigoClasificacionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.CataCodeClassificationResponse ListadoCodigoClasificacion;
        
        public ListadoCodigoClasificacionResponse()
        {
        }
        
        public ListadoCodigoClasificacionResponse(ServiceReferenceSICOP.CataCodeClassificationResponse ListadoCodigoClasificacion)
        {
            this.ListadoCodigoClasificacion = ListadoCodigoClasificacion;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cata.co.cr")]
    public partial class getItemInfo
    {
        
        private CataItemRequest cataInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CataItemRequest cataInfo
        {
            get
            {
                return this.cataInfoField;
            }
            set
            {
                this.cataInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getItemInfoRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cata.co.cr")]
        public ServiceReferenceSICOP.AuthHeader authHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.getItemInfo getItemInfo;
        
        public getItemInfoRequest()
        {
        }
        
        public getItemInfoRequest(ServiceReferenceSICOP.AuthHeader authHeader, ServiceReferenceSICOP.getItemInfo getItemInfo)
        {
            this.authHeader = authHeader;
            this.getItemInfo = getItemInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getItemInfoResponse", WrapperNamespace="http://www.cata.co.cr", IsWrapped=true)]
    public partial class getItemInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.CataItemResponse ItemInfoService;
        
        public getItemInfoResponse()
        {
        }
        
        public getItemInfoResponse(ServiceReferenceSICOP.CataItemResponse ItemInfoService)
        {
            this.ItemInfoService = ItemInfoService;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cata.co.cr")]
    public partial class ListadoSegmentos
    {
        
        private CataSegmentRequest cataInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CataSegmentRequest cataInfo
        {
            get
            {
                return this.cataInfoField;
            }
            set
            {
                this.cataInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListadoSegmentosRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cata.co.cr")]
        public ServiceReferenceSICOP.AuthHeader authHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.ListadoSegmentos ListadoSegmentos;
        
        public ListadoSegmentosRequest()
        {
        }
        
        public ListadoSegmentosRequest(ServiceReferenceSICOP.AuthHeader authHeader, ServiceReferenceSICOP.ListadoSegmentos ListadoSegmentos)
        {
            this.authHeader = authHeader;
            this.ListadoSegmentos = ListadoSegmentos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListadoSegmentosResponse", WrapperNamespace="http://www.cata.co.cr", IsWrapped=true)]
    public partial class ListadoSegmentosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.CataSegmentResponse ListadoSegmentos;
        
        public ListadoSegmentosResponse()
        {
        }
        
        public ListadoSegmentosResponse(ServiceReferenceSICOP.CataSegmentResponse ListadoSegmentos)
        {
            this.ListadoSegmentos = ListadoSegmentos;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cata.co.cr")]
    public partial class ListadoProductos
    {
        
        private CataProductRequest cataInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CataProductRequest cataInfo
        {
            get
            {
                return this.cataInfoField;
            }
            set
            {
                this.cataInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListadoProductosRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cata.co.cr")]
        public ServiceReferenceSICOP.AuthHeader authHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.ListadoProductos ListadoProductos;
        
        public ListadoProductosRequest()
        {
        }
        
        public ListadoProductosRequest(ServiceReferenceSICOP.AuthHeader authHeader, ServiceReferenceSICOP.ListadoProductos ListadoProductos)
        {
            this.authHeader = authHeader;
            this.ListadoProductos = ListadoProductos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListadoProductosResponse", WrapperNamespace="http://www.cata.co.cr", IsWrapped=true)]
    public partial class ListadoProductosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.CataProductResponse ListadoProductos;
        
        public ListadoProductosResponse()
        {
        }
        
        public ListadoProductosResponse(ServiceReferenceSICOP.CataProductResponse ListadoProductos)
        {
            this.ListadoProductos = ListadoProductos;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cata.co.cr")]
    public partial class ListadoAtributos
    {
        
        private CataListadoAtributosRequestBean cataInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CataListadoAtributosRequestBean cataInfo
        {
            get
            {
                return this.cataInfoField;
            }
            set
            {
                this.cataInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListadoAtributosRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://www.cata.co.cr")]
        public ServiceReferenceSICOP.AuthHeader authHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.ListadoAtributos ListadoAtributos;
        
        public ListadoAtributosRequest()
        {
        }
        
        public ListadoAtributosRequest(ServiceReferenceSICOP.AuthHeader authHeader, ServiceReferenceSICOP.ListadoAtributos ListadoAtributos)
        {
            this.authHeader = authHeader;
            this.ListadoAtributos = ListadoAtributos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListadoAtributosResponse", WrapperNamespace="http://www.cata.co.cr", IsWrapped=true)]
    public partial class ListadoAtributosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cata.co.cr", Order=0)]
        public ServiceReferenceSICOP.CataListadoAtributosResponseBean ListadoAtributos;
        
        public ListadoAtributosResponse()
        {
        }
        
        public ListadoAtributosResponse(ServiceReferenceSICOP.CataListadoAtributosResponseBean ListadoAtributos)
        {
            this.ListadoAtributos = ListadoAtributos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface CataWebServiceChannel : ServiceReferenceSICOP.CataWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class CataWebServiceClient : System.ServiceModel.ClientBase<ServiceReferenceSICOP.CataWebService>, ServiceReferenceSICOP.CataWebService
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CataWebServiceClient() : 
                base(CataWebServiceClient.GetDefaultBinding(), CataWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.CataWebServiceSoapPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CataWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CataWebServiceClient.GetBindingForEndpoint(endpointConfiguration), CataWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CataWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CataWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CataWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CataWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CataWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSICOP.DetailCodigoClasificacionResponse> DetailCodigoClasificacionAsync(ServiceReferenceSICOP.DetailCodigoClasificacionRequest request)
        {
            return base.Channel.DetailCodigoClasificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSICOP.ListadoCodigoClasificacionResponse> ListadoCodigoClasificacionAsync(ServiceReferenceSICOP.ListadoCodigoClasificacionRequest request)
        {
            return base.Channel.ListadoCodigoClasificacionAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceSICOP.getItemInfoResponse> ServiceReferenceSICOP.CataWebService.getItemInfoAsync(ServiceReferenceSICOP.getItemInfoRequest request)
        {
            return base.Channel.getItemInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSICOP.getItemInfoResponse> getItemInfoAsync(ServiceReferenceSICOP.AuthHeader authHeader, ServiceReferenceSICOP.getItemInfo getItemInfo)
        {
            ServiceReferenceSICOP.getItemInfoRequest inValue = new ServiceReferenceSICOP.getItemInfoRequest();
            inValue.authHeader = authHeader;
            inValue.getItemInfo = getItemInfo;
            return ((ServiceReferenceSICOP.CataWebService)(this)).getItemInfoAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSICOP.ListadoSegmentosResponse> ListadoSegmentosAsync(ServiceReferenceSICOP.ListadoSegmentosRequest request)
        {
            return base.Channel.ListadoSegmentosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSICOP.ListadoProductosResponse> ListadoProductosAsync(ServiceReferenceSICOP.ListadoProductosRequest request)
        {
            return base.Channel.ListadoProductosAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceSICOP.ListadoAtributosResponse> ListadoAtributosAsync(ServiceReferenceSICOP.ListadoAtributosRequest request)
        {
            return base.Channel.ListadoAtributosAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CataWebServiceSoapPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CataWebServiceSoapPort))
            {
                return new System.ServiceModel.EndpointAddress("http://www.sicop.go.cr:8080/CataItemInfoWS/CataItemInfoWService");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CataWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.CataWebServiceSoapPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CataWebServiceClient.GetEndpointAddress(EndpointConfiguration.CataWebServiceSoapPort);
        }
        
        public enum EndpointConfiguration
        {
            
            CataWebServiceSoapPort,
        }
    }
}
