//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceRecursosHumano
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceRecursosHumano.WS_RecursosHumanosSoap")]
    public interface WS_RecursosHumanosSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonaNombre", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarPersonaNombreResponseBuscarPersonaNombreResult> BuscarPersonaNombreAsync(string Nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonaCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarPersonaCedulaResponseBuscarPersonaCedulaResult> BuscarPersonaCedulaAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraeConstanciasPendientes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.TraeConstanciasPendientesResponseTraeConstanciasPendientesResult> TraeConstanciasPendientesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ColaboradoresXCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ColaboradoresXCedulaAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traeNombresDepartamentos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.traeNombresDepartamentosResponseTraeNombresDepartamentosResult> traeNombresDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ColaboradoresXCodigo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> ColaboradoresXCodigoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/JefeXCedulaColaborador", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.JefeXCedulaColaboradorResponseJefeXCedulaColaboradorResult> JefeXCedulaColaboradorAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUnidadesAdministrativasXCorreo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ObtenerUnidadesAdministrativasXCorreoResponseObtenerUnidadesAdministrativasXCorreoResult> ObtenerUnidadesAdministrativasXCorreoAsync(string Correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUnidadesAdministrativasXCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ObtenerUnidadesAdministrativasXCedulaResponseObtenerUnidadesAdministrativasXCedulaResult> ObtenerUnidadesAdministrativasXCedulaAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerUnidadesAdministrativasXCodigo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ObtenerUnidadesAdministrativasXCodigoResponseObtenerUnidadesAdministrativasXCodigoResult> ObtenerUnidadesAdministrativasXCodigoAsync(string Codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EstadoBoleta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.EstadoBoletaResponseEstadoBoletaResult> EstadoBoletaAsync(string NumBoleta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerDiasFeriados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.traerDiasFeriadosResponseTraerDiasFeriadosResult> traerDiasFeriadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerInfoConfig", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.traerInfoConfigResponseTraerInfoConfigResult> traerInfoConfigAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPersonaIngresoCedulas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarPersonaIngresoCedulasResponseBuscarPersonaIngresoCedulasResult> BuscarPersonaIngresoCedulasAsync(string Cedulas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CantidadDiasDisponible", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> CantidadDiasDisponibleAsync(string Cedulas);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarPeriodosCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarPeriodosCedulaResponseBuscarPeriodosCedulaResult> BuscarPeriodosCedulaAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DependenciaXCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.DependenciaXCedulaResponseDependenciaXCedulaResult> DependenciaXCedulaAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/restaFechas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> restaFechasAsync(System.DateTime fecha1, System.DateTime fecha2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerDiasDisponiblesXCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> traerDiasDisponiblesXCedulaAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerTodasFechas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.traerTodasFechasResponseTraerTodasFechasResult> traerTodasFechasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerFechaIngreso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TraerFechaIngresoAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerFechaControl", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TraerFechaControlAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerIngreso", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> TraerIngresoAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarUsuarioCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarUsuarioCedulaResponseBuscarUsuarioCedulaResult> BuscarUsuarioCedulaAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DiasFeriados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.DiasFeriadosResponseDiasFeriadosResult> DiasFeriadosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarNombreCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarNombreCedulaResponseBuscarNombreCedulaResult> BuscarNombreCedulaAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarUsuarioXCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarUsuarioXCedulaResponseBuscarUsuarioXCedulaResult> BuscarUsuarioXCedulaAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Es_Especial", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> Es_EspecialAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UsuarioConcejo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> UsuarioConcejoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EsUsuarioActivo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> EsUsuarioActivoAsync(string Cedula, string id_usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EsUsuarioSeguridad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> EsUsuarioSeguridadAsync(string usuario, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CorreoSeguridad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CorreoSeguridadAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CorreoRRHH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.CorreoRRHHResponseCorreoRRHHResult> CorreoRRHHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCorreoXNumeroBoleta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> obtenerCorreoXNumeroBoletaAsync(string numBoleta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/diferenciaEntreSolicitudEInicio", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> diferenciaEntreSolicitudEInicioAsync(string numBoleta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TraerCantidadFeriadoEntreFechas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> TraerCantidadFeriadoEntreFechasAsync(System.DateTime fecha1, System.DateTime fecha2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CorreoSeguridadCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> CorreoSeguridadCedulaAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarCedulaUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> BuscarCedulaUsuarioAsync(string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/insertarReporteIncapacidad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> insertarReporteIncapacidadAsync(string Cedula, string ObservacionesColaborador, string Id_TipoDocumento, int Id_InstitucioEmite, string Fecha_Inicio, string Fecha_Final);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/guardarSolicitudConstancia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> guardarSolicitudConstanciaAsync(string Cedula, int Id_DetalleEstado, string ObservacionesSolicitante, int Id_TipoConstancia);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/agregarDiaFeriado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> agregarDiaFeriadoAsync(string Fecha_Dia_Feriado, string Observacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editarDiaFeriado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> editarDiaFeriadoAsync(string Fecha_Dia_Feriado, string Observacion, string Id_Dia_Feriado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EditarContanciaPendiente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> EditarContanciaPendienteAsync(string Id, string ObservacionesRRHH, string Id_DetalleEstado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editarCorreoSeguridad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> editarCorreoSeguridadAsync(string cedula, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editarCorreoSeguridadUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> editarCorreoSeguridadUsuarioAsync(string usuario, string correo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/editarClaveSeguridad", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> editarClaveSeguridadAsync(string cedula, string clave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/eliminarDiaFeriado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> eliminarDiaFeriadoAsync(string Id_Dia_Feriado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/obtenerCredencialesVs2020", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.obtenerCredencialesVs2020ResponseObtenerCredencialesVs2020Result> obtenerCredencialesVs2020Async(string TipDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarFechasSolicitadas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ValidarFechasSolicitadasResponseValidarFechasSolicitadasResult> ValidarFechasSolicitadasAsync(string fechaInicio, string fechaFin, string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/guardarBitacora", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> guardarBitacoraAsync(string MOVIMIENTO, string DSC_BITACORA, string ID_SISTEMA, string ID_USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarDiasFeriados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> AgregarDiasFeriadosAsync(string MOVIMIENTO, string DSC_BITACORA, string ID_SISTEMA, string ID_USUARIO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DiasDisfrute", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<int> DiasDisfruteAsync(System.DateTime Fecha_Inicio, System.DateTime Fecha_Fin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitudesParaAprobar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.SolicitudesParaAprobarResponseSolicitudesParaAprobarResult> SolicitudesParaAprobarAsync(string id_Usuario, string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitudesParaAnularRRHH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.SolicitudesParaAnularRRHHResponseSolicitudesParaAnularRRHHResult> SolicitudesParaAnularRRHHAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitudesParaAnular", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.SolicitudesParaAnularResponseSolicitudesParaAnularResult> SolicitudesParaAnularAsync(string id_Usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitudesMostrar", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.SolicitudesMostrarResponseSolicitudesMostrarResult> SolicitudesMostrarAsync(string Cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerCadenaBoleta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> traerCadenaBoletaAsync(string id_Boleta, string estado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerFechaSolicitudBoleta", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> traerFechaSolicitudBoletaAsync(string id_Boleta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/traerNombreXCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> traerNombreXCedulaAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EsRRHH", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> EsRRHHAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EsJefe", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> EsJefeAsync(string cedula);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBoletaCorreo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<bool> enviarBoletaCorreoAsync(string asunto, string mensajeHtml, string CorreoRecibe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enviarBoletaCorreoAdjunto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.enviarBoletaCorreoAdjuntoResponse> enviarBoletaCorreoAdjuntoAsync(ServiceReferenceRecursosHumano.enviarBoletaCorreoAdjuntoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitudObservacionJefatura", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SolicitudObservacionJefaturaAsync(string id_solicitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerJefesPorNombreOCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ObtenerJefesPorNombreOCedulaResponseObtenerJefesPorNombreOCedulaResult> ObtenerJefesPorNombreOCedulaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ObtenerColaboradoresPorNombreOCedula", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ObtenerColaboradoresPorNombreOCedulaResponseObtenerColaboradoresPorNombreOCedulaResult> ObtenerColaboradoresPorNombreOCedulaAsync(string prefixText, string cedulaQuienConsulta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SolicitudesParaAprobarAsync", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<string> SolicitudesParaAprobarAsyncAsync(string cedula);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class BuscarPersonaNombreResponseBuscarPersonaNombreResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class BuscarPersonaCedulaResponseBuscarPersonaCedulaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class TraeConstanciasPendientesResponseTraeConstanciasPendientesResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class traeNombresDepartamentosResponseTraeNombresDepartamentosResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class JefeXCedulaColaboradorResponseJefeXCedulaColaboradorResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ObtenerUnidadesAdministrativasXCorreoResponseObtenerUnidadesAdministrativasXCorreoResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ObtenerUnidadesAdministrativasXCedulaResponseObtenerUnidadesAdministrativasXCedulaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ObtenerUnidadesAdministrativasXCodigoResponseObtenerUnidadesAdministrativasXCodigoResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class EstadoBoletaResponseEstadoBoletaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class traerDiasFeriadosResponseTraerDiasFeriadosResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class traerInfoConfigResponseTraerInfoConfigResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class BuscarPersonaIngresoCedulasResponseBuscarPersonaIngresoCedulasResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class BuscarPeriodosCedulaResponseBuscarPeriodosCedulaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class DependenciaXCedulaResponseDependenciaXCedulaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class traerTodasFechasResponseTraerTodasFechasResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class BuscarUsuarioCedulaResponseBuscarUsuarioCedulaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class DiasFeriadosResponseDiasFeriadosResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class BuscarNombreCedulaResponseBuscarNombreCedulaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class BuscarUsuarioXCedulaResponseBuscarUsuarioXCedulaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class CorreoRRHHResponseCorreoRRHHResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class obtenerCredencialesVs2020ResponseObtenerCredencialesVs2020Result
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ValidarFechasSolicitadasResponseValidarFechasSolicitadasResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SolicitudesParaAprobarResponseSolicitudesParaAprobarResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SolicitudesParaAnularRRHHResponseSolicitudesParaAnularRRHHResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SolicitudesParaAnularResponseSolicitudesParaAnularResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class SolicitudesMostrarResponseSolicitudesMostrarResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarBoletaCorreoAdjunto", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class enviarBoletaCorreoAdjuntoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string asunto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensajeHtml;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string CorreoRecibe;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string NombreDoc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] byteArray;
        
        public enviarBoletaCorreoAdjuntoRequest()
        {
        }
        
        public enviarBoletaCorreoAdjuntoRequest(string asunto, string mensajeHtml, string CorreoRecibe, string NombreDoc, byte[] byteArray)
        {
            this.asunto = asunto;
            this.mensajeHtml = mensajeHtml;
            this.CorreoRecibe = CorreoRecibe;
            this.NombreDoc = NombreDoc;
            this.byteArray = byteArray;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="enviarBoletaCorreoAdjuntoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class enviarBoletaCorreoAdjuntoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool enviarBoletaCorreoAdjuntoResult;
        
        public enviarBoletaCorreoAdjuntoResponse()
        {
        }
        
        public enviarBoletaCorreoAdjuntoResponse(bool enviarBoletaCorreoAdjuntoResult)
        {
            this.enviarBoletaCorreoAdjuntoResult = enviarBoletaCorreoAdjuntoResult;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ObtenerJefesPorNombreOCedulaResponseObtenerJefesPorNombreOCedulaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://tempuri.org/")]
    public partial class ObtenerColaboradoresPorNombreOCedulaResponseObtenerColaboradoresPorNombreOCedulaResult
    {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlElement any1Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="http://www.w3.org/2001/XMLSchema", Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Namespace="urn:schemas-microsoft-com:xml-diffgram-v1", Order=1)]
        public System.Xml.XmlElement Any1
        {
            get
            {
                return this.any1Field;
            }
            set
            {
                this.any1Field = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface WS_RecursosHumanosSoapChannel : ServiceReferenceRecursosHumano.WS_RecursosHumanosSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class WS_RecursosHumanosSoapClient : System.ServiceModel.ClientBase<ServiceReferenceRecursosHumano.WS_RecursosHumanosSoap>, ServiceReferenceRecursosHumano.WS_RecursosHumanosSoap
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public WS_RecursosHumanosSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(WS_RecursosHumanosSoapClient.GetBindingForEndpoint(endpointConfiguration), WS_RecursosHumanosSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_RecursosHumanosSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(WS_RecursosHumanosSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_RecursosHumanosSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(WS_RecursosHumanosSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public WS_RecursosHumanosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarPersonaNombreResponseBuscarPersonaNombreResult> BuscarPersonaNombreAsync(string Nombre)
        {
            return base.Channel.BuscarPersonaNombreAsync(Nombre);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarPersonaCedulaResponseBuscarPersonaCedulaResult> BuscarPersonaCedulaAsync(string Cedula)
        {
            return base.Channel.BuscarPersonaCedulaAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.TraeConstanciasPendientesResponseTraeConstanciasPendientesResult> TraeConstanciasPendientesAsync()
        {
            return base.Channel.TraeConstanciasPendientesAsync();
        }
        
        public System.Threading.Tasks.Task<string> ColaboradoresXCedulaAsync(string Cedula)
        {
            return base.Channel.ColaboradoresXCedulaAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.traeNombresDepartamentosResponseTraeNombresDepartamentosResult> traeNombresDepartamentosAsync()
        {
            return base.Channel.traeNombresDepartamentosAsync();
        }
        
        public System.Threading.Tasks.Task<string> ColaboradoresXCodigoAsync(string codigo)
        {
            return base.Channel.ColaboradoresXCodigoAsync(codigo);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.JefeXCedulaColaboradorResponseJefeXCedulaColaboradorResult> JefeXCedulaColaboradorAsync(string Cedula)
        {
            return base.Channel.JefeXCedulaColaboradorAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ObtenerUnidadesAdministrativasXCorreoResponseObtenerUnidadesAdministrativasXCorreoResult> ObtenerUnidadesAdministrativasXCorreoAsync(string Correo)
        {
            return base.Channel.ObtenerUnidadesAdministrativasXCorreoAsync(Correo);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ObtenerUnidadesAdministrativasXCedulaResponseObtenerUnidadesAdministrativasXCedulaResult> ObtenerUnidadesAdministrativasXCedulaAsync(string Cedula)
        {
            return base.Channel.ObtenerUnidadesAdministrativasXCedulaAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ObtenerUnidadesAdministrativasXCodigoResponseObtenerUnidadesAdministrativasXCodigoResult> ObtenerUnidadesAdministrativasXCodigoAsync(string Codigo)
        {
            return base.Channel.ObtenerUnidadesAdministrativasXCodigoAsync(Codigo);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.EstadoBoletaResponseEstadoBoletaResult> EstadoBoletaAsync(string NumBoleta)
        {
            return base.Channel.EstadoBoletaAsync(NumBoleta);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.traerDiasFeriadosResponseTraerDiasFeriadosResult> traerDiasFeriadosAsync()
        {
            return base.Channel.traerDiasFeriadosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.traerInfoConfigResponseTraerInfoConfigResult> traerInfoConfigAsync(string cedula)
        {
            return base.Channel.traerInfoConfigAsync(cedula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarPersonaIngresoCedulasResponseBuscarPersonaIngresoCedulasResult> BuscarPersonaIngresoCedulasAsync(string Cedulas)
        {
            return base.Channel.BuscarPersonaIngresoCedulasAsync(Cedulas);
        }
        
        public System.Threading.Tasks.Task<int> CantidadDiasDisponibleAsync(string Cedulas)
        {
            return base.Channel.CantidadDiasDisponibleAsync(Cedulas);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarPeriodosCedulaResponseBuscarPeriodosCedulaResult> BuscarPeriodosCedulaAsync(string Cedula)
        {
            return base.Channel.BuscarPeriodosCedulaAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.DependenciaXCedulaResponseDependenciaXCedulaResult> DependenciaXCedulaAsync(string Cedula)
        {
            return base.Channel.DependenciaXCedulaAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<int> restaFechasAsync(System.DateTime fecha1, System.DateTime fecha2)
        {
            return base.Channel.restaFechasAsync(fecha1, fecha2);
        }
        
        public System.Threading.Tasks.Task<int> traerDiasDisponiblesXCedulaAsync(string Cedula)
        {
            return base.Channel.traerDiasDisponiblesXCedulaAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.traerTodasFechasResponseTraerTodasFechasResult> traerTodasFechasAsync()
        {
            return base.Channel.traerTodasFechasAsync();
        }
        
        public System.Threading.Tasks.Task<string> TraerFechaIngresoAsync(string Cedula)
        {
            return base.Channel.TraerFechaIngresoAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<string> TraerFechaControlAsync(string Cedula)
        {
            return base.Channel.TraerFechaControlAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<string> TraerIngresoAsync(string Cedula)
        {
            return base.Channel.TraerIngresoAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarUsuarioCedulaResponseBuscarUsuarioCedulaResult> BuscarUsuarioCedulaAsync(string Cedula)
        {
            return base.Channel.BuscarUsuarioCedulaAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.DiasFeriadosResponseDiasFeriadosResult> DiasFeriadosAsync()
        {
            return base.Channel.DiasFeriadosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarNombreCedulaResponseBuscarNombreCedulaResult> BuscarNombreCedulaAsync(string Cedula)
        {
            return base.Channel.BuscarNombreCedulaAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.BuscarUsuarioXCedulaResponseBuscarUsuarioXCedulaResult> BuscarUsuarioXCedulaAsync(string cedula)
        {
            return base.Channel.BuscarUsuarioXCedulaAsync(cedula);
        }
        
        public System.Threading.Tasks.Task<bool> Es_EspecialAsync(string cedula)
        {
            return base.Channel.Es_EspecialAsync(cedula);
        }
        
        public System.Threading.Tasks.Task<string> UsuarioConcejoAsync()
        {
            return base.Channel.UsuarioConcejoAsync();
        }
        
        public System.Threading.Tasks.Task<bool> EsUsuarioActivoAsync(string Cedula, string id_usuario)
        {
            return base.Channel.EsUsuarioActivoAsync(Cedula, id_usuario);
        }
        
        public System.Threading.Tasks.Task<bool> EsUsuarioSeguridadAsync(string usuario, string clave)
        {
            return base.Channel.EsUsuarioSeguridadAsync(usuario, clave);
        }
        
        public System.Threading.Tasks.Task<string> CorreoSeguridadAsync(string usuario)
        {
            return base.Channel.CorreoSeguridadAsync(usuario);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.CorreoRRHHResponseCorreoRRHHResult> CorreoRRHHAsync()
        {
            return base.Channel.CorreoRRHHAsync();
        }
        
        public System.Threading.Tasks.Task<string> obtenerCorreoXNumeroBoletaAsync(string numBoleta)
        {
            return base.Channel.obtenerCorreoXNumeroBoletaAsync(numBoleta);
        }
        
        public System.Threading.Tasks.Task<int> diferenciaEntreSolicitudEInicioAsync(string numBoleta)
        {
            return base.Channel.diferenciaEntreSolicitudEInicioAsync(numBoleta);
        }
        
        public System.Threading.Tasks.Task<int> TraerCantidadFeriadoEntreFechasAsync(System.DateTime fecha1, System.DateTime fecha2)
        {
            return base.Channel.TraerCantidadFeriadoEntreFechasAsync(fecha1, fecha2);
        }
        
        public System.Threading.Tasks.Task<string> CorreoSeguridadCedulaAsync(string cedula)
        {
            return base.Channel.CorreoSeguridadCedulaAsync(cedula);
        }
        
        public System.Threading.Tasks.Task<string> BuscarCedulaUsuarioAsync(string usuario)
        {
            return base.Channel.BuscarCedulaUsuarioAsync(usuario);
        }
        
        public System.Threading.Tasks.Task<string> insertarReporteIncapacidadAsync(string Cedula, string ObservacionesColaborador, string Id_TipoDocumento, int Id_InstitucioEmite, string Fecha_Inicio, string Fecha_Final)
        {
            return base.Channel.insertarReporteIncapacidadAsync(Cedula, ObservacionesColaborador, Id_TipoDocumento, Id_InstitucioEmite, Fecha_Inicio, Fecha_Final);
        }
        
        public System.Threading.Tasks.Task<string> guardarSolicitudConstanciaAsync(string Cedula, int Id_DetalleEstado, string ObservacionesSolicitante, int Id_TipoConstancia)
        {
            return base.Channel.guardarSolicitudConstanciaAsync(Cedula, Id_DetalleEstado, ObservacionesSolicitante, Id_TipoConstancia);
        }
        
        public System.Threading.Tasks.Task<string> agregarDiaFeriadoAsync(string Fecha_Dia_Feriado, string Observacion)
        {
            return base.Channel.agregarDiaFeriadoAsync(Fecha_Dia_Feriado, Observacion);
        }
        
        public System.Threading.Tasks.Task<string> editarDiaFeriadoAsync(string Fecha_Dia_Feriado, string Observacion, string Id_Dia_Feriado)
        {
            return base.Channel.editarDiaFeriadoAsync(Fecha_Dia_Feriado, Observacion, Id_Dia_Feriado);
        }
        
        public System.Threading.Tasks.Task<string> EditarContanciaPendienteAsync(string Id, string ObservacionesRRHH, string Id_DetalleEstado)
        {
            return base.Channel.EditarContanciaPendienteAsync(Id, ObservacionesRRHH, Id_DetalleEstado);
        }
        
        public System.Threading.Tasks.Task<string> editarCorreoSeguridadAsync(string cedula, string correo)
        {
            return base.Channel.editarCorreoSeguridadAsync(cedula, correo);
        }
        
        public System.Threading.Tasks.Task<string> editarCorreoSeguridadUsuarioAsync(string usuario, string correo)
        {
            return base.Channel.editarCorreoSeguridadUsuarioAsync(usuario, correo);
        }
        
        public System.Threading.Tasks.Task<string> editarClaveSeguridadAsync(string cedula, string clave)
        {
            return base.Channel.editarClaveSeguridadAsync(cedula, clave);
        }
        
        public System.Threading.Tasks.Task<string> eliminarDiaFeriadoAsync(string Id_Dia_Feriado)
        {
            return base.Channel.eliminarDiaFeriadoAsync(Id_Dia_Feriado);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.obtenerCredencialesVs2020ResponseObtenerCredencialesVs2020Result> obtenerCredencialesVs2020Async(string TipDoc)
        {
            return base.Channel.obtenerCredencialesVs2020Async(TipDoc);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ValidarFechasSolicitadasResponseValidarFechasSolicitadasResult> ValidarFechasSolicitadasAsync(string fechaInicio, string fechaFin, string cedula)
        {
            return base.Channel.ValidarFechasSolicitadasAsync(fechaInicio, fechaFin, cedula);
        }
        
        public System.Threading.Tasks.Task<string> guardarBitacoraAsync(string MOVIMIENTO, string DSC_BITACORA, string ID_SISTEMA, string ID_USUARIO)
        {
            return base.Channel.guardarBitacoraAsync(MOVIMIENTO, DSC_BITACORA, ID_SISTEMA, ID_USUARIO);
        }
        
        public System.Threading.Tasks.Task<string> AgregarDiasFeriadosAsync(string MOVIMIENTO, string DSC_BITACORA, string ID_SISTEMA, string ID_USUARIO)
        {
            return base.Channel.AgregarDiasFeriadosAsync(MOVIMIENTO, DSC_BITACORA, ID_SISTEMA, ID_USUARIO);
        }
        
        public System.Threading.Tasks.Task<int> DiasDisfruteAsync(System.DateTime Fecha_Inicio, System.DateTime Fecha_Fin)
        {
            return base.Channel.DiasDisfruteAsync(Fecha_Inicio, Fecha_Fin);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.SolicitudesParaAprobarResponseSolicitudesParaAprobarResult> SolicitudesParaAprobarAsync(string id_Usuario, string cedula)
        {
            return base.Channel.SolicitudesParaAprobarAsync(id_Usuario, cedula);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.SolicitudesParaAnularRRHHResponseSolicitudesParaAnularRRHHResult> SolicitudesParaAnularRRHHAsync()
        {
            return base.Channel.SolicitudesParaAnularRRHHAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.SolicitudesParaAnularResponseSolicitudesParaAnularResult> SolicitudesParaAnularAsync(string id_Usuario)
        {
            return base.Channel.SolicitudesParaAnularAsync(id_Usuario);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.SolicitudesMostrarResponseSolicitudesMostrarResult> SolicitudesMostrarAsync(string Cedula)
        {
            return base.Channel.SolicitudesMostrarAsync(Cedula);
        }
        
        public System.Threading.Tasks.Task<string> traerCadenaBoletaAsync(string id_Boleta, string estado)
        {
            return base.Channel.traerCadenaBoletaAsync(id_Boleta, estado);
        }
        
        public System.Threading.Tasks.Task<string> traerFechaSolicitudBoletaAsync(string id_Boleta)
        {
            return base.Channel.traerFechaSolicitudBoletaAsync(id_Boleta);
        }
        
        public System.Threading.Tasks.Task<string> traerNombreXCedulaAsync(string cedula)
        {
            return base.Channel.traerNombreXCedulaAsync(cedula);
        }
        
        public System.Threading.Tasks.Task<bool> EsRRHHAsync(string cedula)
        {
            return base.Channel.EsRRHHAsync(cedula);
        }
        
        public System.Threading.Tasks.Task<bool> EsJefeAsync(string cedula)
        {
            return base.Channel.EsJefeAsync(cedula);
        }
        
        public System.Threading.Tasks.Task<bool> enviarBoletaCorreoAsync(string asunto, string mensajeHtml, string CorreoRecibe)
        {
            return base.Channel.enviarBoletaCorreoAsync(asunto, mensajeHtml, CorreoRecibe);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.enviarBoletaCorreoAdjuntoResponse> ServiceReferenceRecursosHumano.WS_RecursosHumanosSoap.enviarBoletaCorreoAdjuntoAsync(ServiceReferenceRecursosHumano.enviarBoletaCorreoAdjuntoRequest request)
        {
            return base.Channel.enviarBoletaCorreoAdjuntoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.enviarBoletaCorreoAdjuntoResponse> enviarBoletaCorreoAdjuntoAsync(string asunto, string mensajeHtml, string CorreoRecibe, string NombreDoc, byte[] byteArray)
        {
            ServiceReferenceRecursosHumano.enviarBoletaCorreoAdjuntoRequest inValue = new ServiceReferenceRecursosHumano.enviarBoletaCorreoAdjuntoRequest();
            inValue.asunto = asunto;
            inValue.mensajeHtml = mensajeHtml;
            inValue.CorreoRecibe = CorreoRecibe;
            inValue.NombreDoc = NombreDoc;
            inValue.byteArray = byteArray;
            return ((ServiceReferenceRecursosHumano.WS_RecursosHumanosSoap)(this)).enviarBoletaCorreoAdjuntoAsync(inValue);
        }
        
        public System.Threading.Tasks.Task<string> SolicitudObservacionJefaturaAsync(string id_solicitud)
        {
            return base.Channel.SolicitudObservacionJefaturaAsync(id_solicitud);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ObtenerJefesPorNombreOCedulaResponseObtenerJefesPorNombreOCedulaResult> ObtenerJefesPorNombreOCedulaAsync()
        {
            return base.Channel.ObtenerJefesPorNombreOCedulaAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceRecursosHumano.ObtenerColaboradoresPorNombreOCedulaResponseObtenerColaboradoresPorNombreOCedulaResult> ObtenerColaboradoresPorNombreOCedulaAsync(string prefixText, string cedulaQuienConsulta)
        {
            return base.Channel.ObtenerColaboradoresPorNombreOCedulaAsync(prefixText, cedulaQuienConsulta);
        }
        
        public System.Threading.Tasks.Task<string> SolicitudesParaAprobarAsyncAsync(string cedula)
        {
            return base.Channel.SolicitudesParaAprobarAsyncAsync(cedula);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_RecursosHumanosSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_RecursosHumanosSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.WS_RecursosHumanosSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://gestiones-administrativas.curridabat.go.cr/Ws-recursoshumanos.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.WS_RecursosHumanosSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://gestiones-administrativas.curridabat.go.cr/Ws-recursoshumanos.asmx");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            WS_RecursosHumanosSoap,
            
            WS_RecursosHumanosSoap12,
        }
    }
}
